# Generated by Django 5.2.7 on 2025-10-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="sku_images/"),
        ),
    ]
