# Generated by Django 5.2.7 on 2025-10-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dailysales",
            index=models.Index(
                fields=["-date", "branch"], name="sales_daily_date_829df4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailysales",
            unique_together={("branch", "sku", "date")},
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["-created_at"], name="sales_sale_created_66311a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["branch", "-created_at"], name="sales_sale_branch__97dba9_idx"
            ),
        ),
    ]
