# Generated by Django 5.2.7 on 2025-10-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("predicted_quantity", models.IntegerField(default=0)),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("actual_quantity", models.IntegerField(blank=True, null=True)),
                ("method", models.CharField(default="moving_average", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-forecast_date", "branch", "sku"],
            },
        ),
    ]
