# Generated by Django 5.2.7 on 2025-10-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forecast", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="inventory.branch",
            ),
        ),
        migrations.AddField(
            model_name="forecast",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="inventory.sku",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["-forecast_date", "branch"],
                name="forecast_fo_forecas_629001_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forecast",
            unique_together={("branch", "sku", "forecast_date")},
        ),
    ]
